name: Publish GBNF (Javascript) to NPM
on:
  push:
    tags:
      - "gbnfjs-v*"
jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          registry-url: 'https://registry.npmjs.org'

      - uses: pnpm/action-setup@v3
        name: Install pnpm
        with:
          version: 8
          run_install: false

      - name: Get pnpm store directory
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV

      - uses: actions/cache@v4
        name: Setup pnpm cache
        with:
          path: ${{ env.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Install dependencies
        working-directory: ./packages/gbnfjs
        run: pnpm install

      - name: Build package
        working-directory: ./packages/gbnfjs
        run: pnpm build

      - name: 'Check build output'
        working-directory: ./packages/gbnfjs
        run: 'pnpm build:check'

      - run: pnpm publish --no-git-checks --provenance --access public
        working-directory: ./packages/gbnfjs
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

permissions:
  id-token: write
