name: "Cut Release for GBNFjs"

on:
  push:
    tags:
      - "gbnfjs-v*"

jobs:
  tagged-release:
    name: "Cut Release for GBNFjs"
    runs-on: "ubuntu-latest"

    steps:
      - name: 'Checkout repository'
        uses: actions/checkout@v4
        with:
          lfs: 'true'

      - uses: actions/setup-node@v4
        with:
          node-version: '20.x'

      - uses: pnpm/action-setup@v3
        name: Install pnpm
        with:
          version: 8
          run_install: false

      - name: Get pnpm store directory
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV

      - uses: actions/cache@v4
        name: Setup pnpm cache
        with:
          path: ${{ env.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Install dependencies
        working-directory: ./packages/gbnfjs
        run: pnpm install

      - name: 'Build'
        working-directory: ./packages/gbnfjs
        run: 'pnpm build'

      - name: 'Check build output'
        working-directory: ./packages/gbnfjs
        run: 'pnpm build:check'

      - name: 'Pack'
        working-directory: ./packages/gbnfjs
        run: 'pnpm pack'

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          fail_on_unmatched_files: true
          generate_release_notes: true
          files: |
            packages/gbnfjs/gbnf-*.tgz
