name: Cut release from new tag

on:
  push:
    tags:
      - "js*"
      - "py*"

jobs:
  tagged-release:
    name: "Tagged Release"
    runs-on: "ubuntu-latest"

    steps:
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          generate_release_notes: true
