name: 'Python Tests'
on:
  # push:
  pull_request:
    paths:
      # This covers _anything_ under the specific package directory, as well as
      # this workflow file, and relevant JS files at the root.
      - 'packages/gbnfpy/**'
      - '.github/workflows/tests-py.yaml'
      # Notes:
      #
      # `paths` works _per commit_. That means that if you push a commit
      # that only changes the README, a paths '**.ts' won't run, and then
      # the PR will not be mergable.
      #
      # Also, relative paths (./packages) don't work. Take off the dot. 

env:
  FORCE_COLOR: "1"

jobs:
  lint:
    name: 'Lint'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: 3.11
          cache: pip
          cache-dependency-path: ./packages/gbnfpy/dev-deps/python3.11/lint.txt

      - run: pip install -U pip setuptools wheel 
        working-directory: ./packages/gbnfpy

      - name: Install dependencies
        run: pip install -r dev-deps/python3.11/lint.txt
        working-directory: ./packages/gbnfpy

      - run: ruff check .

  test:
    name: 'Unit Tests for ${{ matrix.pyversion }}'
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          # https://github.com/actions/python-versions/blob/main/versions-manifest.json
          # - pyversion: "3.12"
          - pyversion: "3.11"
            enable_coverage: true
          - pyversion: "3.10"
            more_hypothesis_examples_if_cron: true
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.pyversion }}
          cache: pip
          cache-dependency-path: ./packages/gbnfpy/${{ format('python{0}', matrix.pyversion) }}/test.txt

      - run: python -m pip install -U pip setuptools wheel 
        working-directory: ./packages/gbnfpy

      - name: Install dev dependencies
        run: pip install -r dev-deps/${{ format('python{0}', matrix.pyversion) }}/test.txt
        working-directory: ./packages/gbnfpy

      - name: Install dependencies
        run: pip install .
        working-directory: ./packages/gbnfpy

      - run: python -m pytest
        working-directory: ./packages/gbnfpy

      - name: Upload coverage to Codecov  # https://github.com/codecov/codecov-action
        uses: codecov/codecov-action@eaaf4bedf32dbdc6b720b63067d99c4d77d6047d
        if: matrix.enable_coverage
        with:
          verbose: true
          files: ./packages/gbnfpy/coverage.xml
          fail_ci_if_error: false  # https://github.com/codecov/codecov-action/issues/557

  build:
    name: 'Build'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: 3.11
          cache: pip
          cache-dependency-path: ./packages/gbnfpy/dev-deps/python3.11/build.txt
      - uses: pnpm/action-setup@v2
        with:
          version: 8

      - run: pip install -U pip setuptools wheel 
        working-directory: ./packages/gbnfpy

      - name: Install build dependencies
        run: pip install -r dev-deps/python3.11/build.txt
        working-directory: ./packages/gbnfpy

      - name: Install dependencies
        run: pip install .
        working-directory: ./packages/gbnfpy

      - run: make build_package
        working-directory: ./packages/gbnfpy

      - name: Check dist
        working-directory: ./packages/gbnfpy
        run: twine check dist/*
